from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator

class User(models.Model): # the user model includes the admin, employee and security guard
    username = models.CharField(max_length=200, validators=[MinLengthValidator(4,"Minimum 4 characters are required"),])
    email = models.EmailField()
    mobile = models.IntegerField(validators=[MinLengthValidator(10, 'Enter a 10 digit mobile number'), MaxLengthValidator(10)])
    pic = models.ImageField(upload_to='media')
    admin = models.BooleanField(default=False)
    
class Visitor(models.Model):
    name = models.CharField(max_length=200, validators=[MinLengthValidator(2,'Minimum 2 Characters are required')]) # name of the visitor
    purpose = models.CharField(max_length=200, validators=[MinLengthValidator(4, 'Minimum 4 characters are required')]) # purpose of visit
    mobile = models.IntegerField(validators=[MinLengthValidator(10, 'Enter a 10 digit mobile number'), MaxLengthValidator(10)]) # mobile no. of the visitor
    email = models.EmailField() # email address of the visitor
    no_of_people = models.IntegerField() # no. of visitors
    in_time = models.DateField(auto_now_add=False) # in time of the visitor, added automatically
    out_time = models.DateField(auto_now=True) # out time of the visitor added automatically
    employee_to_visit = models.CharField(max_length=200) # enter the employee whom the visitor is visiting
    token = models.CharField(max_length=200) # token(autogenerated)
    qrcode = models.ImageField() # qr code generated from the token
    user = models.ForeignKey(User, on_delete=models.PROTECT) # link to the User table, to store which user allowed the entry
    