# Generated by Django 3.1.1 on 2020-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20201025_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='out_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
