# Generated by Django 3.1.1 on 2020-10-26 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20201026_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='mobile',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000, 'Enter a 10 digit mobile number'), django.core.validators.MaxValueValidator(10000000000, 'Enter a 10 digit mobile number')]),
        ),
    ]
