# Generated by Django 3.1.1 on 2020-10-26 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_auto_20201026_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(1000000000, 'Enter a 10 digit mobile number'), django.core.validators.MaxValueValidator(10000000000, 'Enter a 10 digit mobile number')]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
