# Generated by Django 3.1.1 on 2020-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20201026_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
