# Generated by Django 3.1.1 on 2020-10-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_auto_20201026_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='employee_to_visit',
        ),
        migrations.AddField(
            model_name='visitor',
            name='photo_id',
            field=models.ImageField(null=True, upload_to='media/photo_id'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='photo_id_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='media/qrcodes'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
