# Generated by Django 3.1.1 on 2020-10-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_auto_20201027_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='media/photo_id'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='photo_id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='media/qrcodes'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
