# Generated by Django 3.1.1 on 2020-10-27 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_auto_20201027_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visit In time'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='mobile',
            field=models.IntegerField(verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Minimum 2 Characters are required')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='no_of_people',
            field=models.IntegerField(verbose_name='No of people'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visit Out Time'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='media/photo_id', verbose_name='Photo Id'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='photo_id_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Photo Id Number'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(4, 'Minimum 4 characters are required')], verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='media/qrcodes', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.employee', verbose_name='Employee to visit'),
        ),
    ]
