# Generated by Django 3.1.1 on 2020-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0012_visitor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visit_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Token assigned to the Visitor'),
        ),
    ]
