# Generated by Django 3.1.1 on 2021-01-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0015_auto_20210121_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visit In time'),
        ),
    ]
