# Generated by Django 3.1.1 on 2021-01-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_auto_20210121_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='expected_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visit In time'),
        ),
    ]
