# Generated by Django 3.1.1 on 2021-01-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0017_visitor_expected_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='session_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='expected_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected Visit In Time'),
        ),
    ]
