# Generated by Django 3.1.1 on 2021-01-30 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_auto_20210121_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('safety_training', models.BooleanField(verbose_name='Is Given Safety Training?')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entry.visitor', verbose_name='Visitor:')),
            ],
        ),
    ]
