# Generated by Django 3.1.1 on 2021-01-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_visitordetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitorDetails',
            new_name='VisitorsDetail',
        ),
    ]
