# Generated by Django 3.1.1 on 2021-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0020_auto_20210130_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorsdetail',
            name='safety_training',
            field=models.BooleanField(verbose_name='Is Safety Training Given?'),
        ),
    ]
