# Generated by Django 3.1.1 on 2021-01-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0022_auto_20210131_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='visit_token',
        ),
    ]
