# Generated by Django 3.1.1 on 2021-02-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0023_remove_visitor_visit_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='qrcode',
        ),
    ]
