# Generated by Django 3.1.1 on 2021-02-15 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0025_auto_20210215_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='mobile',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Mobile number'),
        ),
    ]
