# Generated by Django 3.1.1 on 2021-02-15 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0027_auto_20210215_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorsdetail',
            name='photo_id_number',
        ),
        migrations.AddField(
            model_name='visitorsdetail',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Photo Id Number'),
        ),
    ]
