# Generated by Django 3.1.1 on 2021-02-15 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0028_auto_20210216_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorsdetail',
            name='mobile',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Photo Id Number'),
        ),
    ]
