# Generated by Django 3.1.1 on 2021-05-17 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0029_auto_20210216_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^([0|\\+[0-9]{1,5})?([0-9]{10})$')]),
        ),
    ]
