# Generated by Django 3.1.1 on 2021-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0030_auto_20210517_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsdetail',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visitor In Time'),
        ),
        migrations.AddField(
            model_name='visitorsdetail',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visitor Out Time'),
        ),
    ]
