# Generated by Django 3.1.1 on 2021-06-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0031_auto_20210609_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsdetail',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Token'),
        ),
    ]
